### ISSUE TITLE
IC format in log file has changed

### ISSUE THREAD

**Issue by marvinhagemeister** [andrewiggins/v8-deopt-viewer#24]
Looks like there is one new column in the CSV and we trip over that. Ours has only 9 parsers whereas recent versions of v8 write 10 columns.

Our parser:

https://github.com/andrewiggins/v8-deopt-viewer/blob/6af15a4e33a5a16b5523f2d4a57f3ec634f55d75/packages/v8-deopt-parser/src/propertyICParsers.js#L68-L78

V8: https://source.chromium.org/chromium/chromium/src/+/main:v8/tools/system-analyzer/processor.mjs;l=69-72?q=StoreIC&ss=chromium%2Fchromium%2Fsrc&start=41

EDIT: This folder might also be of interest: https://source.chromium.org/chromium/chromium/src/+/main:v8/tools/system-analyzer/

**Comment by marvinhagemeister** [comment]
Some more information:

Node 15/16:

```txt
StoreIC,0x3107e6a754d5,676125,534,44,X,X,0x000000000000,map,,
```

Node <= 14

```txt
StoreIC,0xf2e574a7855,534,44,X,X,0x000000000000,map,,
```

Not sure what the third number is referring to.

**Comment by andrewiggins** [comment]
I believe it is the current time: https://source.chromium.org/chromium/chromium/src/+/main:v8/src/logging/log.cc;l=1789;drc=293ee2451677a4456a02b3dea9e0ef2a557db505
